export const STORAGE_KEYS = {
  auth: "auth",
  wallet: "wallet",
} as const;

export const APP_ROUTES = {
  signin: "/signin",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  onboarding: "/onboarding",
  dashboard: "/dashboard",
  profile: "/profile",
  user: "/user",
  editProfile: "/edit-profile",
  wallet: "/wallet",
  depositMoney: "/deposit-money",
  getMoney: "/get-money",
  transfer: "/transfer",
  invite: "/invite",
  agentDeposit: "/agent-deposit",
  history: "/history",
  settings: "/settings",
  changePassword: "/change-password",
  language: "/language",
  activeSessions: "/active-sessions",
  leaderboard: "/leaderboard",
  tournament: "/tournament",
  missions: "/missions",
  notifications: "/notifications",
  dailyBonus: "/daily-bonus",
  walletHistory: "/wallet-history",
  withdrawalStatus: "/withdrawal-status",
  transaction: "/transaction",
  // NEW 6-PILLAR PLATFORM ROUTES
  learn: "/learn",
  courses: "/courses",
  skills: "/skills",
  build: "/build",
  projects: "/projects",
  challenge: "/challenge",
  competitions: "/competitions",
  competitionDetail: "/competitions/:id",
  mentors: "/mentors",
  mentorship: "/mentorship",
  jobs: "/jobs",
  internships: "/internships",
  achievements: "/achievements",
  activity: "/activity",
  admin: {
    panel: "/admin/panel",
    users: "/admin/users",
    deposits: "/admin/deposits",
    withdrawals: "/admin/withdrawals",
    tournaments: "/admin/tournaments",
    missions: "/admin/missions",
    analytics: "/admin/analytics",
    agents: "/admin/agents",
    skills: "/admin/skills",
    courses: "/admin/courses",
  },
} as const;
